services:
  apache:
    build: apache-php-lamp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./prestashop_8.2.1:/var/www/html
      - ./apache-php-lamp/vhost-apache.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./apache-php-lamp/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./apache-php-lamp/certificados:/etc/ssl/certs
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
    networks:
      redelamplemp:
        aliases:
          - test.lan
  basededatos:
    image: mysql:latest
    container_name: lamp_mysql_dev
    restart: always
    env_file:
      - .env.dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}      
    volumes:
      - datos:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      redelamplemp:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp_phpmyadmin_dev
    restart: always
    depends_on:
      - basededatos
    environment:
      PMA_HOST: basededatos
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      redelamplemp:

  cliente:
    hostname: cliente
    image: brunosct/debian12-cliente-firefox
    networks:
      - redelamplemp
    environment:
    - DISPLAY=${DISPLAY}
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix  
volumes:
  datos:
networks:
  redelamplemp: