version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: lemp_nginx_dev
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./prestashop_8.2.1:/var/www/html
      - ./nginx-lemp/vhost-nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - phpserver
    networks:
      redelamplemp:
        aliases:
          - test.lan

  phpserver:
    build: ./php-lemp
    container_name: lemp_php_dev
    restart: always
    volumes:
      - ./prestashop_8.2.1:/var/www/html
      - ./php-lemp/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      redelamplemp:

  basededatos:
    image: mysql:latest
    container_name: lemp_mysql_dev
    restart: always
    env_file: 
      - .env.dev
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - datos:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      redelamplemp:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lemp_phpmyadmin_dev
    restart: always
    depends_on:
      - basededatos
    environment:
      PMA_HOST: basededatos
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      redelamplemp:

  cliente:
    hostname: cliente
    image: brunosct/debian12-cliente-firefox
    networks:
      - redelamplemp
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  

networks:
  redelamplemp:

volumes:
  datos:
